/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a1;

public class App {

    public static void main(String[] args) {
        Syst system = new Syst();
        system.systemInit();
        system.systemDraw();
    }
}
